### ISSUE TITLE
record a gif screencast

### ISSUE THREAD

**Issue by vvo** [lolilolicon/FFcast#11]
Readers: read the fine wiki: [GIF Howto](https://github.com/lolilolicon/FFcast/wiki/GIF-Howto) (edit by @lolilolicon).

Hello @lolilolicon I discovered this great project and did:

``` shell
ffcast rec hello.gif
```

Now this consumes a lot of space. How can I record an optimized gif screencast, dropping the framerate and optimizing the resulting gif?

Thanks

@vvo never mentioned he wrote [gifify](https://github.com/vvo/gifify) (seen on [GitLab Handbook](https://about.gitlab.com/handbook/product/making-gifs/)) (edit by @lolilolicon).

**Comment by lolilolicon** [comment]
For future reference:
- [How do I convert a video to GIF using ffmpeg, with reasonable quality?](https://superuser.com/questions/556029/how-do-i-convert-a-video-to-gif-using-ffmpeg-with-reasonable-quality/556031#556031)
- [High quality GIF with FFmpeg](http://blog.pkh.me/p/21-high-quality-gif-with-ffmpeg.html)
