### ISSUE TITLE
should allow configurable frame rate

### ISSUE THREAD

**Issue by aspiers** [lolilolicon/FFcast#15]
Looks like [the frame rate is currently hardcoded at 25fps](https://github.com/lolilolicon/FFcast/blob/master/src/subcmd.bash#L137).  It would be better if this was configurable.

**Comment by lolilolicon** [comment]
Indeed, the input frame rate is hard-coded. Why 25fps? I think I just followed the examples in the ffmpeg man page. Since you asked, and it's easy enough, so why not? The commit 62db4aa enables setting frame rate with something like `ffcast rec -r 30 a.mkv`. Enjoy.

**Comment by aspiers** [comment]
Excellent, thanks!  By the way you might enjoy this handy tip: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by lolilolicon** [comment]
Hey thanks for the tip mate!
