### ISSUE TITLE
Does not offset? 

### ISSUE THREAD

**Issue by fbm-static** [lolilolicon/FFcast#16]
Hello,

Thank you so much for the nice tool. However, I'm having a problem. When a select an area through my mouse, the recorded part is from the upperleft-corner of my screen ( instead of upper-left corner of my selection) to the lower-right corner of the selection.

My distro is ArchLinux.
My WM is xmonad.

```
sleep 2 && \
notify-send start && \
ffcast -g 774x533+500+113 -vvv ffmpeg -f x11grab -i $DISPLAY -y -t 8 test.mp4 && \
notify-send end
```

**Comment by lolilolicon** [comment]
It's a case of PEBKAC. Read the man page. Look at the examples section for a quick start. Since you are an Archer, I assume you like reading man pages ;)

**Comment by fbm-static** [comment]
It actually looks like I have to use the "rec" subcommand. hehe.

**Comment by lolilolicon** [comment]
Well, `rec` is convenient if it satisfies your needs, but you can always call `ffmpeg` directly.
