### ISSUE TITLE
brew recipe?

### ISSUE THREAD

**Issue by strages** [lolilolicon/FFcast#18]
Can we get this to a brew recipe?

**Comment by lolilolicon** [comment]
Sorry I'm not familiar with Homebrew, so can't help you there. Besides, I don't think a brew recipe would belong in the source of FFcast, in the same way a PKGBUILD (which I have written and uploaded to the AUR) doesn't belong here. However, if someone comes up with a brew recipe, I'd be happy to link to it in the README.

**Comment by strages** [comment]
No the brew recipe would be part of the https://github.com/Homebrew/homebrew repository and would make for a 1 command install (even for binary), upping the convenience of using your tool!

**Comment by lolilolicon** [comment]
Now you see why I said I'm not familiar with Homebrew :)
Obviously, I'm not in the position to write the recipe. Perhaps try writing it yourself? The dependencies are listed in the README.

**Comment by strages** [comment]
the point was, that i actually never succesfully installed your tool ;) this way it was maybe possible in an easy manner

**Comment by strages** [comment]
but sure :) thanks for the replies! I am myself not familiar with creating brew recipes, but as I didnt get to install it myself succesfully even without a brew recipe I think I am not the one to make such a thing.
