### ISSUE TITLE
Recommended tool for starting/running w/o terminal?

### ISSUE THREAD

**Issue by nmschulte** [lolilolicon/FFcast#19]
I'm invoking ffcast via keybinding from my window manager.  I'm wondering what you might recommend as a solution to e.g. telling ffmpeg I want it to end the recording.  When I run via terminal, I just send ffmpeg SIGINT (CTRL+C) and it seems to work.  When I invoke via `bindsym ... exec ...` w/ i3wm, nada.  Even placing the cursor over the capture window hint/border and sending my WM's `keybind ... kill`, nada.

Thanks, ffcast/xrectsel is great, I just wish it was packaged for Debian too.

**Comment by lolilolicon** [comment]
To terminate the ffmpeg process without access to the terminal, you need to know its PID. A crude way to do this is to use a PID file, e.g. `ffmepg ... & echo $! >FILE`. Or, perhaps make a systemd user unit for it.

However, if I were you, I'd probably just use the i3 scratchpad terminal to run ffcast/ffmpeg; just put it out of the recorded area. To quit recording, activate the scratchpad window and press `q`.

**Comment by nmschulte** [comment]
That's perfect, thanks!  I was unaware of the scratchpad workspace and
commands.  +1

**Comment by lolilolicon** [comment]
Aside from scratchpad (or a drop-down terminal like guake or tilda), [madx/gifcast](https://github.com/madx/gifcast) seems to be a fine alternative (I haven't tried).
