### ISSUE TITLE
Nice to have: option to add small delay before recording

### ISSUE THREAD

**Issue by averissimo** [lolilolicon/FFcast#20]
Sometimes after selecting the area on the screen there are some glitches (see below)

It would be nice to be able to start recording after a certain delay (via option)

I am avoiding this by trimming the beginning of the video afterwards via a script, but I never get to know when these 3 seconds end :)

Having a visual indication by seeing the output of recording after the delay would be a fantastic indicator

![out2xxike6cis](https://cloud.githubusercontent.com/assets/211358/19083311/8a33e0d6-8a59-11e6-9146-e81a0240511b.gif)

**Comment by lolilolicon** [comment]
Would this work for you?
```
ffcast -g $(ffcast -s; sleep 3) rec cast.mp4
```

**Comment by averissimo** [comment]
Brilliant!!

Thanks a lot and fantastic work with ffcast!

**Comment by lolilolicon** [comment]
Hey I added a sub-command for this, because why not; try this,
```
ffcast -s lag 3 rec cast.mp4
```

**Comment by averissimo** [comment]
wow!

subcmd `lag` works great, I just tested it!

**Comment by lolilolicon** [comment]
Thanks for the feedback. I like your enthusiasm! See you :smile:

**Comment by averissimo** [comment]
My enthusiasm is from how freaking great this is :) 

It is the best way so far to take screencasts without any overhead (other than creating the custom scripts, but that's just fun and games :) )

https://gist.github.com/averissimo/3f40deac1ca22cc6658e2b2b56131ccc
