### ISSUE TITLE
Unable to select full Output with xrectsel

### ISSUE THREAD

**Issue by nmschulte** [lolilolicon/FFcast#23]
As I'm lazy, I have `ffcast ...` bound to a key-binding in order to quickly take arbitrary-sized/positioned video recordings.  But, with `xrectsel`, it seems, selecting what I expected to be the entire region of the X11 Output, selects everything but one full row and one full column of pixels.  I assume this is the right most and bottom most row, but am not sure.

Is it possible to enable this functionality?  I feel this is a limitation of `xrectsel`, given your (@lolilolicon) response here: https://github.com/lolilolicon/xrectsel/issues/2#issuecomment-59408340, but having to remember e.g. the number of windows I want to capture is incompatible with my lazy key-binding solution.

It would be neat if I could use ffcast to select an unbounded number of windows (and/or regions / X11 (Xinerama/Xrandr) Outputs / ffcast-allowed selections) and somehow signal that I'm finished.  Perhaps e.g. a right-click or key-stroke (as a signal itself or as a modifier for a selection to indicate that it's the "last" selection).

Any ideas how I may achieve this without modification to ffcast and complex logic/script?

**Comment by lolilolicon** [comment]
Sorry about the late reply.

You're right about the missing row and column from `xrectsel`. We can change this by adding a `+1` in the height & width calculations, if desired.

The way `ffcast` works now, I don't see a solution to your request. You have to do some planning beforehand, then tell it exactly what to do. What you describe seems to indicate a simple GUI with several buttons. My own solution is to work out the exact geometry first (`ffcast ...` without calling a command), and then call `ffcast -g ... rec` to start recording. Hope that helps.

**Comment by nmschulte** [comment]
Is it possible to make `ffcast` support a "select a window by mouse click *OR* a rectangular region by mouse" feature?  Essentially, if I "click" without making a rectangular selection act as `-w` does now (choose the window's geometry), and if I "click" with making a rectangular selection act as `-s` does now (choose the rectangular region).

As for the boundary conditions of the "select a rectangular region," I think all bounds should operate the same: either the pixels under the border are all included, or they are not.  `xrectsel` currently gives a 0x0 selection when clicking a pixel; and 1x1 when "bordering" a 2x2 region ("click, drag 1x1, release").

**Comment by lolilolicon** [comment]
> Is it possible to make `ffcast` support a "_select a window by mouse click_ **_or_** _a rectangular region by mouse_" feature?

There a X region selection tool more powerful than my simple `xrectsel` called [`slop`](https://github.com/naelstrof/slop) by @naelstrof, as mentioned by @rafi in  lolilolicon/xrectsel#2.

Using `slop` you can click to select window, and drag to select region (see also its `-t` option).
You can use it with `ffcast` like this:

    ffcast -g $(slop -q) png

> Also, I'm open to the idea of a script to queue up region selection, using a special sequence (e.g. ALT+click or right-click) for ending selections, if anyone has such a script available.

You can cancel `slop` using a keyboard press (diabled by `-k`), which makes it exit 1. Leveraging this feature, we can make "infinite selections" (until key press):

    ffcast $(while slop -q -n -f '-g %g '; do :; done) png /tmp/test.png
