### ISSUE TITLE
how can i use external command subsitution as a filename

### ISSUE THREAD

**Issue by shufuwa** [lolilolicon/FFcast#25]
i use this command `date +%m-%d-%H:%M:%S` to get the filename for my screenshots, how can i use this as filename with external substitution.

**Comment by lolilolicon** [comment]
Something like ```ffcast <ext_command> "$(date +%m-%d-%H:%M:%S)"```?
Or if you mean to use a literal `%` in arguments to external commands, you need take into account format-string substitution & escape `%` as `%%`, e.g.: ```ffcast <ext_command> %%m-%%d```

**Comment by shufuwa** [comment]
I wanted to add .png or .mkv at the end too

**Comment by lolilolicon** [comment]
Like ```"$(date +%m-%d-%H:%M:%S).png"```?

Honestly, still not sure what you're trying to do.
When asking for help, it's better to be specific & articulate your question / goal fully.

**Comment by shufuwa** [comment]
when i try this `ffcast png "$(date +%m-%d-%H:%M:%S).png"`
it says 
`:: saving to file: 03-14-16:04:45.png`
`[image2 @ 0x5598e6ed4140] Could not open file : 03-14-16:04:45.png`
`av_interleaved_write_frame(): Input/output error`

i am in /tmp dir so i think there's no permission problem

**Comment by shufuwa** [comment]
my bad, i think its a unix thing
