### ISSUE TITLE
Dark overlay on window/selection when recording

### ISSUE THREAD

**Issue by fmorroni** [lolilolicon/FFcast#28]
Hi, I've been using ffcast for a while now for my screen recording needs. It has worked great up until recently when for some reason the recording started adding something like a dark filter over the selection, as shown in the pictures below.

![image](https://github.com/user-attachments/assets/40e2cff2-6f6d-4b96-bae8-73484c12f2dc)
![image](https://github.com/user-attachments/assets/a96f1347-af7a-4eed-9923-08753482801e)

This would only be somewhat annoying if it just affected **during** the recording, but the dark overlay is also visible in the recording itself, which makes recordings almost unusable as they end up really quite dark...

I'm not sure if it is a problem with ffcast itself or with some dependency though. The last commit in this repo is from 9 months ago, and I don't think this bug has been present for that long. But I don't know where else to look, so any tips are welcome. Thanks!

**Comment by ropery** [comment]
This must be due to a change to FFmpeg, perhaps a bug. I don’t see any change in the [documentation](https://www.ffmpeg.org/ffmpeg-all.html#x11grab) though.

**Comment by fmorroni** [comment]
Hmm I see, but you can reproduce the issue right?

**Comment by fmorroni** [comment]
> This must be due to a change to FFmpeg, perhaps a bug. I don’t see any change in the [documentation](https://www.ffmpeg.org/ffmpeg-all.html#x11grab) though.

I just checked doing a screenrec with ffmpeg directly using the `-show_region` flag and it indeed shows the same dark filter. I'll post this issue in the ffmpeg repo, thanks!
